config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new" # needs to be before the show action so doesn't get the same prefix
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy", as: :task_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id]) #
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])#
  end

  def update
    @task = Task.find(params[:id])#
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

private
  #avoid SQL injection
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

def set_task
    @task = Task.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container mt-5 p-5">
  <%= simple_form_for @task do |f| %>
      <%= f.input :title, label:"Task title", error: 'Task title is mandatory, please specify one'  %>
      <%= f.input :details, label:"Task details", hint: 'No special characters.' %>
      <%= f.input :completed, as: :boolean, checked_value: true, unchecked_value: false, label:"Task completed" %>
      <%= f.button :submit %>
    <% end %>
</div>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="containermt-5 p-5">
  <h1 class=""><%= 'My Tasks' %></h1>
  <div>
    <ul class="list-group list-group-flush">
      <% @tasks.each do |task| %>
        <li class="list-group-item "><%= link_to task.title, task_path(task) %></li>
      <% end %>
    </ul>
  </div>



  <p class="btn btn-light link-primary"><strong><%= link_to "Create new task", tasks_new_path %></strong></p>
</div>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<div class="containermt-5 p-5">

  <h1><%= 'My Task' %></h1>
  <h2><%= @task.title %></h2>
  <p><%= @task.details %></p>
  <p><%= @task.completed %></p>
  <div>
    <p class="btn btn-light link-primary"><strong><%= link_to("Go to all my tasks", tasks_path) %></p>
    <p class="btn btn-light link-primary"><strong><%= link_to "Update new task", task_edit_path(@task) %></p>
    <p class="btn btn-light link-primary"><strong><%= link_to "Delete #{@task.title}",
                task_path(@task),
                method: :delete,
              data: { confirm: "Are you sure?" } %></p>
  </div>
</div>